import "./globals.css";

import { Work_Sans } from "next/font/google";
import { ReactNode } from "react";

const WorkSans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "StartlapSCH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="hu">
      <body className={WorkSans.className}>{children}</body>
    </html>
  );
}
