version: '3.5'

services:
  db:
    image: postgres:13.10
    env_file:
      - .env
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      - konzisite_db_folder:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'


  adminer:
    image: adminer
    restart: ${DOCKER_RESTART_POLICY}
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  konzisite_db_folder:

