openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: string
  /submissions:
    post:
      operationId: SubmissionsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSubmissionDto"
      responses:
        "201":
          description: ""
      tags:
        &a1
        - submissions
    get:
      operationId: SubmissionsController_findAll
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a1
  "/submissions/{id}":
    get:
      operationId: SubmissionsController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a1
    patch:
      operationId: SubmissionsController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSubmissionDto"
      responses:
        "200":
          description: ""
      tags: *a1
    delete:
      operationId: SubmissionsController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a1
  /links:
    post:
      operationId: LinksController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLinkDto"
      responses:
        "201":
          description: ""
      tags:
        &a2
        - links
    get:
      operationId: LinksController_findAll
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a2
  "/links/{id}":
    get:
      operationId: LinksController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a2
    patch:
      operationId: LinksController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLinkDto"
      responses:
        "200":
          description: ""
      tags: *a2
    delete:
      operationId: LinksController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a2
  "/links/slug/{slug}":
    get:
      operationId: LinksController_checkSlug
      parameters:
        - name: slug
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a2
info:
  title: Startlap SCH
  description: The Startlap SCH API description
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateCollectionDto:
      type: object
      properties: {}
    UpdateCollectionDto:
      type: object
      properties: {}
    CreateSubmissionDto:
      type: object
      properties: {}
    UpdateSubmissionDto:
      type: object
      properties: {}
    CreateLinkDto:
      type: object
      properties: {}
    UpdateLinkDto:
      type: object
      properties: {}
