name: Code Style Check

on:
  push:
    branches: ['master', 'staging']
  pull_request:
    branches: ['master', 'staging']

jobs:
  check-code-style:
    name: ESLint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npx prettier --check .
